### ISSUE TITLE
Write ip4 127.0.0.1 -> x.x.x.x (Ip Receiver) sendto: invalid argument

### ISSUE THREAD

**Issue by zamzibar-bofh** [ariary/QueenSono#1]
Im trying this Go in my Test environment and this problem occur. maybe in need to test some other OS.

I try with CentOS 8 and CentOS 7.. and have the same issue/problem.
Write ip4 127.0.0.1 -> x.x.x.x (Ip Receiver) sendto: invalid argument

This problem happen in the "sender" machine. occur after running the command """"qssender send file -d 2 -l 127.0.0.1 -r 10.0.0.92 -s 50000 bible.txt"""""
KR
Jose

**Comment by ariary** [comment]
Did you previously encounter issue while using golang ` net icmp` package?

**Comment by zamzibar-bofh** [comment]
Noup,

Never, this is the first time.. but i do not ussualy use net icmp package.

BTW: i try in 3 diferents OS and the same.

KR
Jose

**Comment by ariary** [comment]
It seems that you rather  have an issue regarding network configuration.  Maybe a route via gateway that is not on your LAN.


 1. Could you ping 127.0.0.1? ping 10.0.0.92?
 2. Same thing w/ `traceroute`

**Comment by zamzibar-bofh** [comment]
Hi Ariary,

Yes I can ping the remote network, through my default gateway. and of course I can ping 127.0.0.1 this is the localhost IP.
and with traceroute Yes I can research this IPs.

KR
Jose

**Comment by ariary** [comment]
I could reproduce it. In fact it is not an OS issue. All my test where on the same LAN, I think this is the issue.

Nice finding thank you and need a fix!
Will do my best to fix it asap. If you want to contribute, feel free

**Comment by ariary** [comment]
This [commit](https://github.com/ariary/QueenSono/commit/981f1883254f5de77894fb3c4b5b76c3470bb3d6] should fix the issue 

Could you confirm?

(but it reveals other issues, thank you)
