### ISSUE TITLE
Cannot execute qssender on Mac

### ISSUE THREAD

**Issue by KRiteshchowdary** [ariary/QueenSono#2]
I have started the listening host on my kali(VM with bridge connection. Can ping). I am trying to send a doc of small size from my mac to my kali using the qssender but can't. Required permissions are given. How should I execute this qssender file. I am using the qssender file that I created in my kali along with qsreceiver.

<img width="824" alt="Screenshot 2021-10-21 at 4 24 52 PM" src="https://user-images.githubusercontent.com/44915939/138264238-a397242e-e7ce-4df8-a77c-7b5faa00eff2.png">

**Comment by ariary** [comment]
Does the `net/icmp` golang package work on your Mac ?
